/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_miracore_free: (a: number, b: number) => void;
export const miracore_new: () => number;
export const miracore_preprocess_input: (a: number, b: number, c: number) => any;
export const miracore_calculate_sentiment_advanced: (a: number, b: number, c: number) => any;
export const miracore_calculate_sentiment: (a: number, b: number, c: number) => number;
export const miracore_detect_mood: (a: number, b: number, c: number) => [number, number];
export const miracore_get_dominant_mood: (a: number) => [number, number];
export const miracore_calculate_mood_transition: (a: number, b: number, c: number, d: number) => [number, number];
export const miracore_detect_expression: (a: number, b: number, c: number) => [number, number];
export const miracore_detect_expression_with_intensity: (a: number, b: number, c: number) => any;
export const miracore_blend_expressions: (a: number, b: number, c: number, d: number) => any;
export const miracore_humanize_response: (a: number, b: number, c: number) => [number, number];
export const miracore_build_conversation_context: (a: number, b: number, c: number) => [number, number];
export const miracore_extract_topics: (a: number, b: number, c: number) => [number, number];
export const miracore_generate_riddle: (a: number) => any;
export const miracore_get_offline_response: (a: number) => [number, number];
export const miracore_interpolate_expression: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const miracore_create_expression_interpolator: (a: number, b: number, c: number, d: number, e: number, f: bigint) => any;
export const miracore_interpolate_expression_smooth: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const quick_mood_check: (a: number, b: number) => [number, number];
export const polish_text: (a: number, b: number) => [number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_alloc: () => number;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
